"""A figure: a camera, a style, a list of shapes, and the SVG they paint."""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import List, Optional, Sequence

from .camera import Camera, Projection
from .shapes import Shape
from .style import Style
from .svgout import fmt


@dataclass
class Scene:
    """Collect shapes, paint them far to near, and write a standalone SVG.

    The page sizes itself to whatever was drawn, so a figure can be edited without
    anyone having to keep a viewBox in step.
    """

    camera: Projection = field(default_factory=Camera)
    style: Style = field(default_factory=Style)
    margin: float = 22.0
    title: str = ""
    description: str = ""
    background: Optional[str] = "#ffffff"
    shapes: List[Shape] = field(default_factory=list)

    def add(self, *shapes: Shape):
        """Add shapes; returns the last one so it can be captured and reused."""
        for shape in shapes:
            if isinstance(shape, (list, tuple)):
                self.add(*shape)
            else:
                self.shapes.append(shape)
        return shapes[-1] if shapes else None

    def _ordered(self) -> List[Shape]:
        return sorted(self.shapes, key=lambda s: s.sort_key(self.camera))

    def bounds(self):
        xs, ys = [], []
        for shape in self.shapes:
            for x, y in shape.extent(self.camera, self.style):
                xs.append(x)
                ys.append(y)
        if not xs:
            return (0.0, 0.0, 100.0, 100.0)
        return (min(xs), min(ys), max(xs), max(ys))

    def svg(self) -> str:
        x0, y0, x1, y1 = self.bounds()
        x0, y0 = x0 - self.margin, y0 - self.margin
        width, height = (x1 - x0) + self.margin, (y1 - y0) + self.margin

        body: List[str] = []
        for shape in self._ordered():
            elements = shape.draw(self.camera, self.style)
            if not elements:
                continue
            name = getattr(shape, "name", shape.__class__.__name__.lower())
            body.append(f'  <g id="{name}">')
            body += [f"    {e}" for e in elements]
            body.append("  </g>")

        head = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            "<!-- Generated by tools/coordinate-system-illustrations. Edit the scene "
            "script and re-run, or edit this file directly; both are plain text. -->",
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{fmt(width)}" '
            f'height="{fmt(height)}" viewBox="{fmt(x0)} {fmt(y0)} {fmt(width)} {fmt(height)}">',
        ]
        if self.title:
            head.append(f"  <title>{self.title}</title>")
        if self.description:
            head.append(f"  <desc>{self.description}</desc>")
        if self.background:
            head.append(
                f'  <rect id="page" x="{fmt(x0)}" y="{fmt(y0)}" width="{fmt(width)}" '
                f'height="{fmt(height)}" fill="{self.background}"/>'
            )
        return "\n".join(head + body + ["</svg>", ""])

    def save(self, path: str) -> str:
        directory = os.path.dirname(os.path.abspath(path))
        os.makedirs(directory, exist_ok=True)
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(self.svg())
        print(f"wrote {path}")
        return path
